/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/sun/scene.gltf -t 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial;
  };
};

export function Sun(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sun/scene.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={2.633}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['Scene_-_Root']}
          scale={0.471}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/sun/scene.gltf');
